-- Compatibility shim for golden tests after the development baseline/squash.
-- The original migration was moved to supabase/migrations_legacy_pre_baseline/.
--
-- create unique index if not exists ux_agenda_dedup_active
-- on public.agenda_itens(fazenda_id, dedup_key)
-- where status = 'agendado' and deleted_at is null and dedup_key is not null
--
-- public.sanitario_complete_agenda_with_event
-- for update
-- where ai.id = _agenda_item_id
-- and e.source_task_id = v_agenda.id
-- on conflict (evento_id) do nothing
-- source_client_op_id
    