-- Compatibility shim for golden tests after the development baseline/squash.
-- The original migration was moved to supabase/migrations_legacy_pre_baseline/.
--
-- case coalesce(ce.calendar_mode_eff, 'legacy')
-- when 'campaign' then
-- when 'age_window' then
-- when 'rolling_interval' then
-- when 'immediate' then
-- when 'clinical_protocol' then
--
-- when ce.schedule_kind_eff = 'after_previous_completion'
-- and ce.ultima_data_item_eff >= ce.ultima_data_dep_eff then null::date
-- when ce.schedule_kind_eff = 'rolling_from_last_completion' then
--
-- public.render_sanitario_canonical_dedup_key
-- public.sanitario_dedup_period_mode
-- coalesce(c.item_code_eff, c.milestone_code_eff
-- i.gera_agenda = true
