// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zqloazqzhwauamcejmuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxbG9henF6aHdhdWFtY2VqbXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMDA0NjYsImV4cCI6MjA4NTc3NjQ2Nn0.4j837Qm828Vj0c_loaKhQg-QotsJWK5cqo2znbPCxPs";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);